### ISSUE TITLE
About pretrained model.

### ISSUE THREAD

**Issue by zeng-yifei** [fu123456/TSHRNet#1]
Really solid work! Congrats to be accepted by ICCV.

BTW, I am curious to know whether the pretrained models be released in the near future. Hope for your answer! :-)

**Comment by fu123456** [comment]
They are already available.
https://github.com/fu123456/TSHRNet/tree/main#pretrained-models

**Comment by zeng-yifei** [comment]
Oh, I'm sorry I didn't notice that. I should apologize for my carelessness. 

Anyway, Thank you for your reply!
