### ISSUE TITLE
高分辨率的合成图片，效果一般

### ISSUE THREAD

**Issue by sucy171106** [fu123456/TSHRNet#4]
![image](https://github.com/user-attachments/assets/496c3297-0168-4520-9540-fce95ae093ac)![image](https://github.com/user-attachments/assets/645b270a-2bf1-4d53-b599-b3c4825ddae2)
我输入了800×800的合成图片，尝试了size=768，size=256。后者效果如上图，前者很多黄色的色块，很奇怪。

**Comment by fu123456** [comment]
May be due to the domain gap between the training images and your test images. The model you used is the re-trained model on your own data?
