### ISSUE TITLE
How can we get the specular residue ground truth for training?

### ISSUE THREAD

**Issue by xiyangcai** [fu123456/TSHRNet#6]
_Specular residue_ is provided in SHIR and SSHR for training, and _Tone Correction_ can be obtained by the matlab script. 

The PSD dataset, however, didn't provide _specular residue_/_highlight intensity_ as ground truth. Is there a script for preprocessing PSD for its specular residue images?

**Comment by fu123456** [comment]
Specular residue is only the difference between the input and its diffuse image. You need to write very simple code to implement.

**Comment by xiyangcai** [comment]
Thank you for your timely and valuable response!
